apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp-pod
    spec:
      containers:
        - name: hospitalService
          image: svathsan/hospitalService:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
  selector:
    matchLabels:
      app: myapp-pod